version: '3.4'

services:
  ui:
    image: 'profile_app'
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      